#!/usr/bin/env node
/**
 * Reclaim disk after a Windows package build.
 *
 * Removes gulp/package intermediates. Keeps packaging/dist Setup.exe by default.
 *
 * Flags:
 *   --dist     also wipe packaging/dist
 *   --zip-only remove portable .zip from dist (keep Setup.exe)
 */
import { spawnSync } from 'node:child_process';
import {
  existsSync,
  readdirSync,
  rmSync,
  unlinkSync,
  writeFileSync,
  readFileSync,
  mkdtempSync,
} from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = new Set(process.argv.slice(2));
const wipeDist = args.has('--dist');
const zipOnly = args.has('--zip-only');

function nukeDir(absPath) {
  if (!existsSync(absPath)) {
    console.log(`[clean] skip (missing) ${absPath}`);
    return;
  }
  console.log(`[clean] remove ${absPath}`);
  if (process.platform === 'win32') {
    // Robocopy /MIR empty dir is the reliable way to wipe huge locked-ish trees
    const empty = mkdtempSync(join(tmpdir(), 'wc-empty-'));
    spawnSync('robocopy', [empty, absPath, '/MIR', '/R:1', '/W:1', '/NFL', '/NDL', '/NJH', '/NJS', '/nc', '/ns', '/np'], {
      stdio: 'ignore',
      env: process.env,
    });
    spawnSync('cmd.exe', ['/c', 'rmdir', '/s', '/q', absPath], { stdio: 'ignore', env: process.env });
    spawnSync('cmd.exe', ['/c', 'rmdir', '/s', '/q', empty], { stdio: 'ignore', env: process.env });
    if (!existsSync(absPath)) return;
  }
  try {
    rmSync(absPath, { recursive: true, force: true });
  } catch (err) {
    console.warn(`[clean] partial failure on ${absPath}: ${err instanceof Error ? err.message : err}`);
  }
}

const targets = [
  join(root, 'VSCode-win32-x64'),
  join(root, 'VSCode-win32-arm64'),
  join(root, 'vscode', 'out-vscode'),
  join(root, 'vscode', 'out-vscode-min'),
  join(root, 'vscode', 'out'),
  // Transpiled build sources — regenerated by the gulp build, previously missed
  // here, so it survived every "clean" and went stale across upstream syncs.
  join(root, 'vscode', 'out-build'),
  join(root, 'vscode', '.build'),
];

for (const t of targets) {
  nukeDir(t);
}

const distDir = join(root, 'packaging', 'dist');
if (wipeDist) {
  nukeDir(distDir);
} else if (existsSync(distDir) && zipOnly) {
  for (const name of readdirSync(distDir)) {
    if (name.endsWith('.zip')) {
      console.log(`[clean] remove ${join(distDir, name)}`);
      unlinkSync(join(distDir, name));
    }
  }
}

if (existsSync(distDir) && !wipeDist) {
  const lines = [];
  for (const name of readdirSync(distDir).filter((n) => n.endsWith('.exe') || n.endsWith('.zip'))) {
    const full = join(distDir, name);
    const hash = createHash('sha512').update(readFileSync(full)).digest('hex');
    lines.push(`${hash}  ${name}`);
  }
  writeFileSync(join(distDir, 'SHA512SUMS'), lines.length ? `${lines.join('\n')}\n` : '', 'utf8');
  console.log('[clean] refreshed packaging/dist/SHA512SUMS');
}

console.log('[clean] done — re-run package:windows-portable to rebuild VSCode-win32-*');
